# Site wide configuration
source                   : .tmp/src
destination              : .tmp/dist

title                    : "Xander Krieg"
description              : "Cultural-Clinical Psychologist and Researcher"
logo                     : /assets/images/site-logo.png
teaser                   : /assets/images/default-teaser.png
locale                   : "en_US"
words_per_minute         : 200
title_separator          : "×"

repository               : “xkrieg/xkrieg.github.io"
url                      : "https://xkrieg.github.io"

twitter:
  username               : “xkrieg”

social:
  name                   : "Xander Krieg"
    - ""
    - ""
    - ""
    - ""
    - ""

google_site_verification : “”
bing_site_verification   : ""
alexa_site_verification  : ""
yandex_site_verification : ""

google_ad-client         : “”
google_ad-slot           : “”
google_analytics         : “”

# Site owner
author:
  name                   : “Xander “Krieg
  url                    : "http://xanderkrieg.com”
  bio                    : "Cultural-Clinical Psychologist and Researcher"
  picture                : ""
  twitter                : “xkrieg”
  facebook               : ""
  instagram              : ""
  tumblr                 : ""
  github                 : ""
  google_plus            : ""

# Staticman comments
staticman:
  allowedFields          : ["name", "email", "url", "message"]
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "src/_data/comments/{options.slug}"
  requiredFields         : ["name", "message"]
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"

# Jekyll configuration
permalink                : /:categories/:title/
lsi                      : false
future                   : false
show_drafts              : false
markdown                 : kramdown
kramdown:
  toc_levels             : 1..3
  input                  : GFM
  hard_wrap              : false
  auto_ids               : true
  entity_output          : as_char
  smart_quotes           : lsquo,rsquo,ldquo,rdquo
  enable_coderay         : false
highlighter              : rouge
keep_files:
  - .git
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# Plugins
gems:
  - jekyll-archives
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag

# Collections
collections:
  faqs:
    output    : true
    permalink : /:collection/:path/
    title     : FAQs
  components:
    output    : false
  colors:
    output    : false

# Front Matter Defaults
defaults:
  # Blog Articles
  - scope:
      path: _posts/articles
      type: posts
    values:
      layout: page
      category: articles
      read_time: true
      breadcrumbs:
        - label: "Blog Articles"
          url: /articles/
  # Mastering Paper
  - scope:
      path: _posts/mastering-paper
      type: posts
    values:
      layout: page
      category: mastering-paper
      read_time: true
      comments: true
      breadcrumbs:
        - label: "Mastering Paper by 53"
          url: /mastering-paper/
  # PaperFaces
  - scope:
      path: _posts/paperfaces
      type: posts
    values:
      layout: work
      category: paperfaces
      breadcrumbs:
        - label: "PaperFaces Portraits"
          url: /paperfaces/
      work: "Illustration"
      seo:
        type: "CreativeWork"
  # Procreate Paintings
  - scope:
      path: _posts/procreate
      type: posts
    values:
      layout: work
      category: procreate-paintings
      breadcrumbs:
        - label: "Procreate Paintings"
          url: /procreate-paintings/
      work: "Illustration"
      seo:
        type: "CreativeWork"
  # TIL
  - scope:
      path: _posts/til
      type: posts
    values:
      layout: page
      category: til
      read_time: true
      breadcrumbs:
        - label: "Today I Learned"
          url: /til/
  # Tiny Paintings
  - scope:
      path: _posts/tiny-paintings
      type: posts
    values:
      layout: work
      category: tiny-paintings
      breadcrumbs:
        - label: "Tiny Paintings"
          url: /tiny-paintings/
      work: "Illustration"
      seo:
        type: "CreativeWork"
  # Work
  - scope:
      path: _posts/work
      type: posts
    values:
      layout: work
      category: work
      breadcrumbs:
        - label: "Work"
          url: /work/
      seo:
        type: "CreativeWork"
  # FAQs
  - scope:
      path: _faqs
      type: faqs
    values:
      layout: page
      read_time: true
      breadcrumbs:
        - label: "Frequently Asked Questions"
          url: /faqs/
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

# Plugin: jekyll-archives
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag_index
  permalinks:
    tag: /tag/:name/
